# http://rosalind.info/problems/dna/

_str = "GAGCTCCAGGCTGGTACTGCATAGCGCCGACGATTGATCACGCCCCTAGGAAGATGTTGAGCAGGGACCATTACAAACAGAGCGCTCTTGATCGGCGGAGTTATTGTTTCAGGGGCCACGCTGGCCCAAATCGATGTCAATCATCTTCAAGAGCTTACAACTCAATCATCAGGCTGCGTTCCATATACTTATGCTCGTTCCCGTCTCGCTTACAGTACGCTAGGCCGAATCAGACGCATCCGTCCGATAAAGGTATGGATTCATCACGGTCTAGTATAAGTCAGGGGGCTACGCCTATGAGCCCACACCCAGCTACGCGACTATGAGCACCTACCAAAACATGATTTCCAATTGTCATTCGTAATAAACTCTCACTCAAACCTTACACCGTGTAGAGCAATCGCAAGTCGTTTCTTCAAGACGCCTTCTCGGACGCTCAACCCATTGCAGACCCTAGAAGCAAACAACGGAGGAACTGGCTCCACAGCTCTAGTTCCCAGACTGAATATTCGGCCAGGGACCGAGATGAAGTCAAGACAAGAGTAGAAAGGATAACCAGCCGCAGTGAGCACCGACGCCGTAGCAAACGTTAAGCATCAATACTCTGAAGGAGCGCGCCGTCCAGTGAGCCCCATGAATAGTACGACCTTAAAAGCCCTGTCCCAATTTAAGGTTCCAGGTCAGATGTGCCCTAGTCCGTCGTCCAGGATGTCAAGGGCCGGAGGCTCGGCCCTCAGTCGCTGACTAGAGACCATGTTGGCAGACCGCTGGGCACACCGCCACTCCGATCGGTCGTCCATCCACCTGCTCGCAACTTGGAAAGCCCTAATATTTCCCACTGGCTCTATATCATTCGAATGATCGCGCATCATGATGCAACAGATTGGTCCCGTGCTAGAATCACAATCGACACCGATCACGAGGAAAAACGACGGGCAACTCTTTGGATTCCTGCGGCCTGACAGACTTCTAAAGAT"

dictionary = {
                "A": 0,
                "C": 0,
                "G": 0,
                "T": 0
             }

for letter in _str:
    if letter in dictionary:
        dictionary[letter] += 1

print(dictionary)